export declare const EventType: {
    readonly OS_CREATED_NO_TECHNICIAN: "OS_CREATED_NO_TECHNICIAN";
    readonly OS_TECHNICIAN_ASSIGNED: "OS_TECHNICIAN_ASSIGNED";
    readonly OS_TECHNICIAN_ASSUMED: "OS_TECHNICIAN_ASSUMED";
    readonly OS_COMPLETED: "OS_COMPLETED";
    readonly OS_APPROVED: "OS_APPROVED";
    readonly OS_REJECTED: "OS_REJECTED";
    readonly OS_UNASSIGNED_ALERT: "OS_UNASSIGNED_ALERT";
    readonly EQUIPMENT_CREATED: "EQUIPMENT_CREATED";
    readonly EQUIPMENT_MOVED: "EQUIPMENT_MOVED";
    readonly EQUIPMENT_WARRANTY_EXPIRING: "EQUIPMENT_WARRANTY_EXPIRING";
    readonly PREVENTIVE_GENERATED: "PREVENTIVE_GENERATED";
    readonly PREVENTIVE_UPCOMING: "PREVENTIVE_UPCOMING";
    readonly MAINTENANCE_OVERDUE: "MAINTENANCE_OVERDUE";
    readonly USER_CREATED: "USER_CREATED";
    readonly USER_DEACTIVATED: "USER_DEACTIVATED";
    readonly DAILY_SUMMARY: "DAILY_SUMMARY";
};
export type EventType = (typeof EventType)[keyof typeof EventType];
//# sourceMappingURL=alert-rule.enum.d.ts.map